export const SELECIONAR_CLIENTE = 'SELECIONAR_CLIENTE';
export const SELECIONAR_PRODUTO = 'SELECIONAR_PRODUTO';
export const QUANTIDADE_PRODUTOS = 'QUANTIDADE_PRODUTOS';
export const ATUALIZAR_TOTAL = 'ATUALIZAR_TOTAL';
